### ISSUE TITLE
xml:lang

### ISSUE THREAD

**Issue by Mestyan** [ProjectJaraid/jaraid_source#99]
It appears, of course, that we mark-up wrongly as what we mean on xml:lang="en" is not that that piece of data is in English but that it is in Latin characters. Similarly xml:lang="ar"  means rather that that data is in Arabic characters. I see that you started to insert the xml:lang="ar-Latn-x-ijmes" attribute in the case of transcribed Arabic persNames and this should be done later with name/title elements as well. Just a note for the future.

**Comment by Mestyan** [comment]
or, actually, since it appears universal, we can simply replace xml:lang="en" with xml:lang="Latn" ? @tillgrallert I did not find an attribute in the TEI dictionary for transliteration

**Comment by Mestyan** [comment]
Hugh suggest "und-Latn" or "mul-Latn" instead of the "en" values

**Comment by tillgrallert** [comment]
I assume this relates to cases when we actually want to indicate that something is in Latin script without specifying a language as opposed to the majority of cases where `@xml:lang="en"` is plainly wrong. Is that correct? Anyway, I always support more specific expressiveness.


–––––––––––––––––––––––––––––––––––––––––––
Till Grallert


"'cloud computing' is just a euphemism for 'some dark bunker in Idaho or Utah.'” (E.Morozov)

Please avoid using email accounts subject to unmitigated scrutiny by private companies and government agencies and reply to till.grallert AT posteo.de.

Use encryption whenever possible. Tools for encrypting your emails with PGP (Pretty Good Privacy) can be found at http://www.gpg4win.org/ (Windows) and https://gpgtools.org (Mac OSX). Open Whisper Systems's Signal provides encrypted messaging and VoIP for all major platforms (https://signal.org). Jitsi (https://jitsi.org/) provides open source encrypted VoIP services. Adium (OSX), Jitsi, and ChatSecure (iOS) support OTR (Off The Record) encryption for Jabber, Google Talk, Facebook chat etc. If you want to replace Dropbox etc., with a decentralised and fully encrypted alternative have a look at Resilio Sync (https://www.resilio.com/).

**Comment by Mestyan** [comment]
yes, actually in most of our markup the "en" value is absolutely wrong. But I guess some of your XSLT uses the "en" value right? So let's not change anything now, just think about it, and we can discuss it in our next session

**Comment by tillgrallert** [comment]
No XSLT transformations run on the master file trust the `@xml:lang="en"` as it is mostly wrong. So you can change it at any time you want. The issue is different for the authority file, where `@xml:lang="en"` has the semantics supposed by the TEI.
–––––––––––––––––––––––––––––––––––––––––––
Till Grallert


"'cloud computing' is just a euphemism for 'some dark bunker in Idaho or Utah.'” (E.Morozov)

Please avoid using email accounts subject to unmitigated scrutiny by private companies and government agencies and reply to till.grallert AT posteo.de.

Use encryption whenever possible. Tools for encrypting your emails with PGP (Pretty Good Privacy) can be found at http://www.gpg4win.org/ (Windows) and https://gpgtools.org (Mac OSX). Open Whisper Systems's Signal provides encrypted messaging and VoIP for all major platforms (https://signal.org). Jitsi (https://jitsi.org/) provides open source encrypted VoIP services. Adium (OSX), Jitsi, and ChatSecure (iOS) support OTR (Off The Record) encryption for Jabber, Google Talk, Facebook chat etc. If you want to replace Dropbox etc., with a decentralised and fully encrypted alternative have a look at Resilio Sync (https://www.resilio.com/).

**Comment by Mestyan** [comment]
OK, great! so I will change tonight all xml:lang="en" to xml:lang="und-Latn"

**Comment by Mestyan** [comment]
done
